### ISSUE TITLE
Addition of Review/Trending APIs

### ISSUE THREAD

**Issue by majora2007** [dentolos19/AniListNet#10]
The library is missing Reviews and Trending APIs.

I'm creating this to inform you not to implement as I can take care of it today/tomorrow. Since I'll need this in the near future, might as well get it taken care of for the Friday release.

**Comment by dentolos19** [comment]
Oh, I've forgot to tell you about this.

I noticed an error while I was debugging before release. It was in `GetMediaReviewsAsync`, I think you've made a mistake while making the method. So, I removed the filter in [this commit](https://github.com/dentolos19/AniListNet/commit/030e66af5b9a0a8d4d462b10b05c3c835bfdf458).

I've forgotten to inform you about this before going to school and went ahead to release the new version. Do you need the filter? If yes, I'll try to readd it in the next release.

**Comment by majora2007** [comment]
I noticed that. I personally don't need it. I added it to enhance the API coverage. If I end up needing it, I will raise a PR or reach out.
