### ISSUE TITLE
Bad Serialization for MediaStatus

### ISSUE THREAD

**Issue by majora2007** [dentolos19/AniListNet#16]
I'm seeing occasionally some data results in null MediaStatus and thus the library throws a serialization exception. 

In this case, I was searching for "haru yo, koi" which caused this issue. 

I do see this one entry doesn't have a MediaStatus:
https://anilist.co/manga/164912/Haru-yo-Koi/
```
An unhandled exception was thrown by the application.
Newtonsoft.Json.JsonSerializationException: Error converting value {null} to type 'AniListNet.Objects.MediaStatus'. Path 'data.Page.media[5].status', line 1, position 7579.

```

**Comment by dentolos19** [comment]
Sorry! I wasn't able to notice this issue. I fixed it in [this commit](https://github.com/dentolos19/AniListNet/commit/b8e69b3415cd859ad4d25292625611c33158129d). I'll push another release this Friday.
