### ISSUE TITLE
Hot to get some properties asHtml = true?

### ISSUE THREAD

**Issue by majora2007** [dentolos19/AniListNet#17]
In the codebase, there are instances of properties, like MediaReview:
`[JsonProperty("body")] [GqlParameter("asHtml", false)] public string Body { get; private set; }`

It would be increadibly helpful to be able to get this property as html, as AniList has a custom Markdown implementation, so consuming apps need to implement their own library or mapping to html, which the custom markup.

**Comment by dentolos19** [comment]
I enforced the usage of markdown because this project is closely linked to another project of mine, so I didn't think of having HTML description.

We can add two separate description properties that returns markdown and HTML respectively by using aliases in GraphQL.

```graphql
query {
    Media(id: 1) {
        description(asHtml: true)
        descriptionHtml: description(asHtml: false)
    }
}
```

To implement this, I think I'll need to write a class called `GqlAlias` and then link it to the said properties. And then have the parser add `descriptionHtml:` before the field.

I'll work on it right now.

**Comment by majora2007** [comment]
In your other project, how did you handle rendering the markdown? AniList has many unique syntax that is not markdown compliant.

**Comment by dentolos19** [comment]
I just let the third-party markdown renderers do all the work. There might be some awkward spacing between paragraphs in their markdown/HTML due to the number of `<br>` used, but other than that, it looks fine to me.

**Comment by majora2007** [comment]
Interesting. I have one I'm using but since anilist has non-mardown syntax, I'm having to write a lot of extra hacks. There are a lot of crazy reviews out there.

**Comment by dentolos19** [comment]
> Interesting. I have one I'm using but since anilist has non-mardown syntax, I'm having to write a lot of extra hacks. There are a lot of crazy reviews out there.

I mean... If it works, it works. I rather not touch a functioning renderer if it is working properly, even if it has some imperfections. I'm not paid enough to fix it. 😪

**Comment by dentolos19** [comment]
I've fixed this issue in [this commit](https://github.com/dentolos19/AniListNet/commit/f7daac888d14430feedaa59cf38bf8153906b98f).

> **Note**: I have revamped my GraphQL parsing engine in [this commit](https://github.com/dentolos19/AniListNet/commit/fab9f546672582e3577c2fad3781f969008f5ea3). So if I were to enable a new feature, I would be able to better accommodate them. I am telling you this just in case you want to contribute to this project again. 😉

**Comment by majora2007** [comment]
Thanks. I do expect to contribute to this project in the future.

**Comment by majora2007** [comment]
Any chance you're going to release this with a new version tomorrow?

**Comment by dentolos19** [comment]
> Any chance you're going to release this with a new version tomorrow?

Yup!
