### ISSUE TITLE
You are not authorized to modify this MediaList

### ISSUE THREAD

**Issue by impishlucy** [dentolos19/AniListNet#19]
I have my token from my API Client and aniClient.IsAuthenticated returns true.

But when i want to do aniClient.DeleteMediaEntryAsync(data.Media.Id) or aniClient.SaveMediaEntryAsync(animeId,mutation) i get that error.

**Comment by dentolos19** [comment]
When you're deleting a media entry, you must input the "media entry ID" and not its respective "media ID". Right now, I see that you are using the "media ID" to delete a media entry which the ID, in terms of the media entries, might have belonged to someone else's media entry, therefore it says, `You are not authorized to modify this MediaList`. But for when saving a media entry, you'll need to use the "media ID". See [here](https://github.com/dentolos19/AniListNet/blob/74be5a68ff72af49bcfe45554578a419dac7ba07/src/AniListNet.Tests/UserMutationsTests.cs#L95-L96) for a reference.

This is a fault on my part for not being more descriptive on the comments and parameter names. But I hope this fixes your issue.
