### ISSUE TITLE
Recently Added Methods also required in NugetPackage.

### ISSUE THREAD

**Issue by HassanTaj** [dentolos19/AniListNet#5]
The new methods used to get all anime list collections look really attractive would love to use them.
Hoping to see new methods in a nugetpkg update. 
Kindly, let me know when you will update it.

**Comment by dentolos19** [comment]
Thank you for using my library!

I have been working on some of my other projects, so I haven't been able to update this project yet. I will push a new update once I finish with some of the [todo items](https://github.com/dentolos19/AniListNet#-todo). You can expect this update within a few weeks, so let's be patient.

> **Note**: You can get notified of any updates by watching this repository! 😊

**Comment by HassanTaj** [comment]
It's really been a pleasure using your library!

Completely understandable and patiently awaiting and excited about the updates to the lib. 

**Thank you for prompt response. **
