### ISSUE TITLE
Client Authentication is not working

### ISSUE THREAD

**Issue by DiekoMA** [dentolos19/AniListNet#6]
```cs
string token = "{TOKEN OMMITED FOR OBVIOUS REASONS}";
                AniClient client = new AniClient();
                var _ = await client.TryAuthenticateAsync(token);
                var authedUser = await client.GetAuthenticatedUserAsync();
                `Console.WriteLine(!authedUser.Options.DisplayAdultContent);
```

Seems to return nothing when run

**Comment by dentolos19** [comment]
Have you read the documentation for [authenticating with AniList](https://github.com/dentolos19/AniListNet/wiki/Tutorials#authenticating-with-anilist)?

I've retested your code on my side, and everything went normally as expected so there shouldn't be anything wrong client-side or server-side.

Unfortunately, there's not enough information that I could work with to solve your problem. But here's some suggestions just to make sure...

- The token should be a very long string that is over 1000 characters (in the case of my token)
- Make sure the user has your app listed in [this page](https://anilist.co/settings/apps)
- See whether the authentication was successful by checking the value returned by the function `TryAuthenticateAsync`

**Comment by DiekoMA** [comment]
Ya that's the weird thing, the code is correct, it just doesn't return anything on my end, I have a correct token cause I compared it to the one used in the unit tests but the authenticated status returns nothing as well

**Comment by DiekoMA** [comment]
Could it have something to do with using .net core ?

**Comment by dentolos19** [comment]
Could you try running this exact code...

```cs
using AniListNet;

var client = new AniClient();

var isAuthenticated = await client.TryAuthenticateAsync("eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsImp0aSI6Ijc1NGZmMDhkMjY4NWQ2N2ZjYzA0NTdiOTVhMzMwNDU2ZTc4NzIwNDJlMTFkNzdjMDg5MDQ0NDI1NGQ2YzBkNzA5YTdiZjdhYjU3MWQxMDUxIn0.eyJhdWQiOiI3Mzc1IiwianRpIjoiNzU0ZmYwOGQyNjg1ZDY3ZmNjMDQ1N2I5NWEzMzA0NTZlNzg3MjA0MmUxMWQ3N2MwODkwNDQ0MjU0ZDZjMGQ3MDlhN2JmN2FiNTcxZDEwNTEiLCJpYXQiOjE2NTMyMDQ3NzAsIm5iZiI6MTY1MzIwNDc3MCwiZXhwIjoxNjg0NzQwNzcwLCJzdWIiOiI1MTE0MTQ4Iiwic2NvcGVzIjpbXX0.H0HNwozkDXZARBWpK6tqxdB4mttVcIzSvAujVriJevr9Cw15CmU65v_JK-Qkba9rE_Arc2pPZrooC2hZJrEaMV98teZwTsmbf59lDNObJlcpjRlEsdDGSRxnhC--ZyOywRoOW9Syv0TJZFmXMUrHK3zOictOgS7tohm3y8XW7b-tdgU5ZBGc-mNhlXb2r_CPvW6_Y2_yDZXAab9aLAMgMhmaLrpDGp911m5A7Y6dESKNG18dO17R1iyoBEadKf2qyNq-zKqa3MgLkGhW7FcEM--c3JibsFuE00gE-u-1btgs5SSLzqrYaJ_08ELS7C-0pkUsGPebJk-s8wv_UxeNQoInWDwGrQF3jpYouzTueCwoxGHLhxmerD1ER9K3enlxK2xiq39YtOn1pRdDgOgTeX7xhy3xCZJShQofZ1Tk8Ye1Q_iJCnp5XWqyqSe-DLEQfZDGKNSsHaRofBuMnGftfDeeLfx2Hx9SxdZSRpsqvOu-mzVx9QStXGn6Ej6BE4gUnNp6Z8UEKkLCIXdiAh9EZejxLgze5ygRoYQZfW_DtF9F0iuqVE6t-5LDpiKHuENlYBMsApuJsO_JEj76clVcL_bXLvFnDrDfd2DbpoRilK1WfU1UX8s7vD-CK-KaKv1VVtyKKx-WdtSjro__XoDgPC4o69iGu-S_ISnarT_3Xyw");

if (isAuthenticated)
{
    var user = await client.GetAuthenticatedUserAsync();
    Console.WriteLine("Authentication successful...");
    Console.WriteLine($"ID: {user.Id}");
    Console.WriteLine($"Name: {user.Name}");
}
else
{
    Console.WriteLine("Authentication failed...");
}
```

> **Note**: Don't worry about the token, it belongs to a random account I've created for testing.

This is the code I've used to test token authentication. It should return this output...

```
Authentication successful.
ID: 5114148
Name: cyrilreyes
```

**Comment by DiekoMA** [comment]
I tried it and nothing got outputted to the console

**Comment by DiekoMA** [comment]
i was running it without an async method my bad
