### ISSUE TITLE
User ProfileColor can be a non-enum value

### ISSUE THREAD

**Issue by majora2007** [dentolos19/AniListNet#7]
From some testing, I'm seeing that some users can have a non-enum based profile color. For example, from the following query:
```
{
  Media(id:1){
		recommendations(sort:RATING_DESC) {
      edges {
        node{
          rating,
          mediaRecommendation {
            id,
            idMal,
            title {
              romaji
              english
              native
              userPreferred
            },
            type,
            format,
          },
          user{
            options {
							profileColor
            }
          }
        }
      }
    }
  }
}
```

You will see: 
```
"user": {
                "options": {
                  "profileColor": "#6E5DEF"
                }
              }
```

This may need a breaking change to handle, unless the option exists to provide a CUSTOM Enum that is a safe guard and add custom mapping logic.

**Comment by majora2007** [comment]
I have a fix that does the mapping into a custom enum, if interested.

**Comment by majora2007** [comment]
It might be beneficial to just return a string instead of an enum. This would be most flexible and would be minimal breaking since the enums are using string representation already.

**Comment by dentolos19** [comment]
I've changed it to your suggestion at this [commit](https://github.com/dentolos19/AniListNet/commit/3fa7aea9558b9716e83ce7ec6fe96bb03ec2f497). I've tested it and it should be fixed now. Thanks!

If anything else, please create a new issue. 🙏
